name: news_pulse
description: A new Flutter project.

# Prevent the package from being accidentally published to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Define the version and build number for your application.
version: 1.0.0+2

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons font for iOS style icons
  cupertino_icons: ^1.0.2
  http: any
  webview_flutter: ^3.0.4
  rename: any
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints to encourage good coding practices
  flutter_lints: ^2.0.0

flutter:
  # Ensure the Material Icons font is included
  uses-material-design: true

  # Add assets to your application
  assets:
    - assets/img/placeholder.jfif
    - assets/img/logo.png

  # Uncomment and modify the following section to add custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
